# Generated by Django 5.0.4 on 2024-05-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0002_alter_purchaseorder_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('P', 'pending'), ('CO', 'completed'), ('CA', 'canceled')], max_length=50),
        ),
    ]
